# Use the official SonarQube image from Docker Hub
FROM sonarqube:latest

# Expose the necessary port for SonarQube
EXPOSE 9000

# Set the necessary environment variables (optional)
ENV SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
ENV SONAR_JDBC_USERNAME=sonarqube
ENV SONAR_JDBC_PASSWORD=sonarqube
